#!/usr/bin/env bash
# Re-setting default port of nginx.

sudo sed -i "s/listen 8080/listen 80/" /etc/nginx/sites-enabled/default
sudo sed -i "s/listen \[::\]:8080/listen \[::\]:80/" /etc/nginx/sites-enabled/default
sudo service nginx restart