#!/usr/bin/env bash
#Using what you did for task #0, make your fix short and sweet.

sudo sed -i "s/listen 8080/listen 80/" /etc/nginx/sites-enabled/default
sudo sed -i "s/listen \[::\]:8080/listen \[::\]:80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
