#!/usr/bin/env bash
# Write a Bash script that creates an RSA key pair

Host ubuntu@18.212.218.239
     HostName 18.212.218.239
     User ubuntu
     IdentityFile ~/.ssh/school
     PasswordAuthentication no
